title: GhostLock
description: CVE-2026-43499 futex PI stack UAF 本地提权漏洞利用

baseurl: "/GhostLock"
url: "https://wzhdgithub.github.io"

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: pretty

# 默认布局
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# 插件
plugins:
  - jekyll-seo-tag

# 排除文件
exclude:
  - README.md
  - LICENSE
  - CONTRIBUTING.md
  - SECURITY.md
  - CHANGELOG.md
  - CODE_OF_CONDUCT.md
  - Makefile
  - compile.cmd
  - build.rsp
  - ghostlock
  - .gitignore
